logging:
  level:
    com.study: debug

spring:
  application:
    name: shardingSphere-simple

  shardingsphere:
    # 将运行模式配置为Standalone单机模式（Cluster：集群模式）
    mode:
      type: Standalone
      repository:
        type: JDBC
    # 配置多个数据源
    datasource:
#      真实数据源名称
      names: ds0,ds1
#      druid数据库连接池配置
      common: &common
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        max-active: 500
        initial-size: 3
        min-idle: 3
        max-wait: 60000
        remove-abandoned: true
        remove-abandoned-timeout: 300
        log-abandoned: true
      # 配置第一个数据源
      ds0:
#        引用common配置
        <<: *common
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_sharding_01?useUnicode=true&useSSL=false&characterEncoding=utf8
        username: root
        password: 123456

      # 配置第二个数据源
      ds1:
        # 引用common配置
        <<: *common
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/db_sharding_02?useUnicode=true&useSSL=false&characterEncoding=utf8
        username: root
        password: 123456
    rules:
      sharding:
        # 配置所有分片表
        tables:
          # 首先配置商品表的分片策略
          shoping:
            # 声明商品表所在的真实数据节点（这里先显式声明一个节点测试）
#            actual-data-nodes: ds0.shoping_00,ds0.shoping_01,ds1.shoping_00,ds1.shoping_01
#            inline表达式，使用笛卡尔积算法生成结果：ds0.shoping_00,ds0.shoping_01,ds1.shoping_00,ds1.shoping_01
            actual-data-nodes: ds$->{0..1}.shoping_0$->{0..1}

    props:
      # 日志显示具体的SQL
      sql-show: true

# mybatis-plus 配置内容
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 虽然默认为 true ，但是还是显示去指定下。
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  global-config:
    db-config:
      id-type: none # 虽然 MyBatis Plus 也提供 ID 生成策略，但是还是使用 Sharding-JDBC 的
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:mapper/*.xml


